config/routes.rb
BrainStorm::Application.routes.draw do

   devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

   resources :levels,   :only => [:create, :show, :update, :destroy]
   resources :attempts, :only => [:create]
   
   root :to => "home_page#index"
   match '/home',           :to => 'home_page#index',         :as => 'home' 
   match '/admin',          :to => 'extra_pages#admin',       :as => 'admin' 
   match '/play',           :to => 'levels#play',             :as => 'play'
   match '/leaderboard',    :to => 'extra_pages#leaderboard', :as => 'leaderboard'
   match 'levels/:id/edit', :to => 'extra_pages#edit_level',  :as => 'edit_level'
   match '/rules',          :to => 'extra_pages#rules',       :as => 'rules'
   match 'team',            :to => 'extra_pages#team',       :as => 'team'

end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  attr_accessible :attempt, :level_id, :user_id


  belongs_to :user
  belongs_to :level


end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :is_playable
end

app/models/image.rb
class Image < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/level.rb
class Level < ActiveRecord::Base
  attr_accessible :answer, :next_id, :prev_id, :question, :image
  before_save :sterlize_answer
  mount_uploader :image, ImageUploader

  has_many :attempts

  validates :answer , :presence => true, :length => {:maximum => 50}

 


  def self.set(params)
    next_id = nil
    prev_id = (Level.last and Level.last.id) ? Level.last.id : nil
    params[:prev_id] = prev_id
    level = Level.new(params)
    level
  end

  def sterlize_answer
    self.answer = self.answer.chomp.downcase.gsub(/[\W\n\s]/,'')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  before_create :allot_score

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_name, :college, :provider, :uid, :name
  # attr_accessible :title, :body

  validates :name, :presence => true, :length => {:maximum => 35},
  :format => {:with => /^[A-Za-z ]+$/, :message => " should only have alphabets"}

  validates :user_name, :uniqueness => true, :presence => true, :length => {:maximum => 50}
  validates :college, :presence => true

  has_many :attempts, :dependent => :destroy

def self.find_or_create(auth, signed_in_resource=nil)
   new_record = false
    user = where(:provider => auth.provider, :uid => auth.uid)
    new_record = true if user.empty?
    new_user = where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
    end
      [new_user, new_record]

 end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  private
    
    def allot_score
      self.score = 1
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	

 	def user_admin
 	  unless current_user and current_user.admin?
		redirect_to home_path, :alert => "Restricted area" 
	  end
	end

	def current_level
	  return(Level.last ? Level.last.id : 0) if current_user.admin?
	  current_user.score
	end

	
  def game_playable?
    if (Game.first and Game.first.is_playable) or current_user.admin?
    else
      redirect_to home_path, :notice => "We know YOU Love Brainstorm but it isn't playable yet."
    end
  end

  def sterlize(value)
  	value.chomp.downcase.gsub(/[\W\n\s]/,'')
  end



end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_filter :game_playable?, :only => [:create]

def create 
	@attempt = current_user.attempts.build(params[:attempt])
	@attempt.level_id = current_level
	@level = Level.find(current_level)


	if @attempt.save
		if sterlize(@attempt.attempt).eql? (@level.answer)
			unless current_user.admin?
				current_user.score = @level.next_id
				current_user.last_correct_answer_at = Time.now
				current_user.save
			end
			if (current_user.score == 6)
				redirect_to home_path
			    flash[:success] = "Congratulations YOU have completed the journey"
			else
			  flash[:success] = "Level Cleared"
			  redirect_to level_path(current_level)
			end		
		else
			flash[:error] = "Wrong Answer"
			redirect_to level_path(current_level)
		end
	else
		@attempts = Attempt.find_all_by_user_id_and_level_id(current_user.id, @level.id)
		render 'levels/show'
	end

end

end

app/controllers/extra_pages_controller.rb
class ExtraPagesController < ApplicationController

   before_filter :user_admin, :only => [:admin, :edit_level]

   	def admin
   		@level = Level.new
   		@users = User.all
   	end

   	def leaderboard
   	  @users = User.order('score DESC, last_correct_answer_at ASC, updated_at ASC').paginate(:page => params[:page], :per_page => 50)
   	  @page  = (params[:page].to_i) -1 if params[:page]
   	end

   	def edit_level
   	  @level = Level.find(params[:id])
   	end

      def rules
      end

      def team
      end

end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
 	
 	before_filter :admin_user, :only => [:create, :edit, :update, :destroy]
  before_filter :registered_user, :only => [:show, :play]
   before_filter :game_playable?, :only => [:show, :play]

	def show
	  @level = Level.find(params[:id])
	  @attempt = current_user.attempts.build
	  @attempts = Attempt.find_all_by_user_id_and_level_id(current_user.id, @level.id)
	  redirect_to @level, :notice => "sorry" if params[:redirect_to_correct_location]
	end

	def play
	  redirect_to level_path(current_user.score)
	end

	def create
	  @level = Level.set(params[:level])
	  @level_last = Level.last

	  if @level.save
	    @level_last.update_attributes(:next_id => Level.last.id ) if @level_last
	    flash[:success] = "Level Created"
	    redirect_to @level
	  
	  end
    end

    def update 
      @level = Level.find(params[:id])
      if @level.update_attributes(params[:level])
      	flash[:success] = "Level successfully Updated"
      	redirect_to @level
      else
      	render 'extra_pages/edit_level'
      end
    end



  private
  def admin_user
    redirect_to home_path, notice: "sudo says: YOU SHALL NOT PASS!" unless current_user and current_user.admin?
  end

  def registered_user
    redirect_to home_path, notice: "Register or Sign in to play." unless current_user
    if current_user and not current_user.admin?
      params[:redirect_to_correct_location] = true if params[:id].to_i != current_user.score
      params[:id] = current_user.score
    end
  end
  
   

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  skip_before_filter :authenticate

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
  @user, new_record = User.find_or_create(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      if new_record
        sign_in @user
    
        redirect_to edit_user_registration_path
      else
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      end
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/extra_pages_helper.rb
module ExtraPagesHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/extra_pages/_qaform.html.erb
<h2> ADD LEVEL </h2>

	<% #(@level.new_record?) ? "Add Level #{@current_level + 1}" : "Editing Level #{@level.id}" %>

<%= form_for @level, :html => { :multipart => true } do |f| %>

  <%= f.label :question %>
  <%= f.text_field :question %>
  <br/> <br/>

  <%= f.label :answer %>
  <%= f.text_field :answer%>
  <br/> <br>

  <%= f.file_field :image %> <br/>

<% if @level.new_record? %>
  <%= f.submit "Create" %>
<% else %>
  <%= f.submit "Edit" %>
<% end %>

<% end %>

app/views/extra_pages/_sidebar.html.erb
<ul>
<% Level.order('id').each do |level| %>
  <li> <%= link_to "Level #{level.id}", edit_level_path(level) %></li>

<% end %>
</ul>

app/views/extra_pages/_users_list.html.erb
<div class="table-responsive">
<table class="table table-condensed table-hover table-bordered">
<tr class="warning">
<th class="bl"> Position </th>
<th class="bl"> Username </th>
<th class="bl"> College  </th>
<th class="bl"> Score    </th>
</tr>

<% @users.each_with_index do |user, index| %>
  <tr>
       <% if @page %>
      <td><%= (50 * @page.to_i) + index + 1 %></td>
       <% else %>
    <td> <%= index + 1 %> </td>
     <% end %>  
        <td> <%= user.user_name %> </td>
        <td> <%= user.college %> </td>
        <td> <%= user.score - 1 %> </td>
        
       <% end %>
   </tr>
       </table> 
</div>
    <%= will_paginate @users %>

app/views/extra_pages/admin.html.erb
<h1> Admin Panel </h1>

<%= render 'extra_pages/sidebar' %>
<%= render 'extra_pages/qaform' %>

app/views/extra_pages/edit_level.html.erb
<%= render 'sidebar' %>
<%= render 'qaform' %>

app/views/extra_pages/leaderboard.html.erb
<h1 class="text-center">Leaderboard</h1>

<%= render 'users_list' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang="en">
<head>
  <title>BrainStorm</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap-theme", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body class="container-fluid">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">   <!-- For navbar-->

 <!-- Brand and toggle get grouped for better mobile display -->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
    </button>
  <div class="navbar-brand"><%= link_to image_tag("bsheader.png"), root_path, id: 'logo' %></div>
     </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">

           <li><%= link_to "Rules", rules_path %></li>
           <li><%= link_to "Forum", "https://apps.facebook.com/forumforpages/page/769175719761186", :target => :blank %></li>
          
      <% if current_user.try(:admin?) %>
         <li><%= link_to "Make Game", admin_path %></li>
      <% end %>
          <li><%= link_to "LeaderBoard", leaderboard_path %></li>

      <% if user_signed_in? %>
          <li><%= link_to "Play Game", play_path%></li>
      
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete  %></li>
      <% else %> 
          <li><%= link_to "Sign In", user_session_path %></li>
          <li><%= link_to "SignUp", new_user_registration_path %></li>
      <% end %>
      </ul>
     </div> 
    </nav>


   <div class ="container"><!--for container-->
        <% if flash[:notice] %>
     <div class = "alert alert-info">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:notice] %>
     </div>
     <% end %>
     <% if flash[:alert] %>
     <div class = "alert alert-danger">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:alert] %>
     </div>
     <% end %>
  
<%= yield %>

    <div class="col-md-12 col-xs-12 col-lg-12">
      <footer>
      Our Sponsor: <%= link_to image_tag("obtuseorange.png"), "http://www.facebook.com/obtuseorange", :class=>"image-responsive",:target => :blank %>
      <%= link_to "Our Team", team_path,:class=>"team float-right" %>
    </footer>
    </div>

</div>

</body>
</html>

app/views/layouts/application.html.erb.BACKUP.3486.erb
<!DOCTYPE html>
<html>
<html lang="en">
<head>
  <title>BrainStorm</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap-theme", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">   <!-- For navbar-->

 <!-- Brand and toggle get grouped for better mobile display -->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
    </button>
  <div class="navbar-brand"><%= link_to image_tag("bsheader.png"), root_path, id: 'logo' %></div>
     </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
<<<<<<< HEAD
           <li><%= link_to "Rules", rules_path %></li>
           <li><%= link_to "Forum", root_path %></li>
=======
           <li><%= link_to "Rules", root_path %></li>
           <li><%= link_to "Forum", "https://apps.facebook.com/forumforpages/page/769175719761186", :target => :blank %></li>
>>>>>>> upstream/master
          
      <% if current_user.try(:admin?) %>
         <li><%= link_to "Make Game", admin_path %></li>
      <% end %>
          <li><%= link_to "LeaderBoard", leaderboard_path %></li>

      <% if user_signed_in? %>
           <% if current_user.score == 6 %>
             <h1> Game Completed </h1>
           <% else %>
          <li><%= link_to "Play Game", play_path%></li>
           <% end %>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete  %></li>
      <% else %> 
          <li><%= link_to "Sign In", user_session_path %></li>
          <li><%= link_to "SignUp", new_user_registration_path %></li>
      <% end %>
      </ul>
     </div> 
    </nav>


   <div class ="container"><!--for container-->
        <% if flash[:notice] %>
     <div class = "alert alert-info">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:notice] %>
     </div>
     <% end %>
     <% if flash[:alert] %>
     <div class = "alert alert-danger">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:alert] %>
     </div>
     <% end %>
  
<%= yield %>

    <div class="col-md-12 col-xs-12 col-lg-12">
      <hr>
      <p>Our Sponsor: <%= link_to image_tag("obtuseorange.png"), "http://www.facebook.com/obtuseorange", :class=>"image-responsive" %></p>
    </div>

</div>

</body>
</html>

app/views/layouts/application.html.erb.BACKUP.3837.erb
<!DOCTYPE html>
<html>
<html lang="en">
<head>
  <title>BrainStorm</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap-theme", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">   <!-- For navbar-->

 <!-- Brand and toggle get grouped for better mobile display -->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
    </button>
  <div class="navbar-brand"><%= link_to image_tag("bsheader.png"), root_path, id: 'logo' %></div>
     </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
<<<<<<< HEAD
           <li><%= link_to "Rules", rules_path %></li>
           <li><%= link_to "Forum", root_path %></li>
=======
           <li><%= link_to "Rules", root_path %></li>
           <li><%= link_to "Forum", "https://apps.facebook.com/forumforpages/page/769175719761186", :target => :blank %></li>
>>>>>>> upstream/master
          
      <% if current_user.try(:admin?) %>
         <li><%= link_to "Make Game", admin_path %></li>
      <% end %>
          <li><%= link_to "LeaderBoard", leaderboard_path %></li>

      <% if user_signed_in? %>
           <% if current_user.score == 6 %>
             <h1> Game Completed </h1>
           <% else %>
          <li><%= link_to "Play Game", play_path%></li>
           <% end %>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete  %></li>
      <% else %> 
          <li><%= link_to "Sign In", user_session_path %></li>
          <li><%= link_to "SignUp", new_user_registration_path %></li>
      <% end %>
      </ul>
     </div> 
    </nav>


   <div class ="container"><!--for container-->
        <% if flash[:notice] %>
     <div class = "alert alert-info">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:notice] %>
     </div>
     <% end %>
     <% if flash[:alert] %>
     <div class = "alert alert-danger">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:alert] %>
     </div>
     <% end %>
  
<%= yield %>

    <div class="col-md-12 col-xs-12 col-lg-12">
      <hr>
      <p>Our Sponsor: <%= link_to image_tag("obtuseorange.png"), "http://www.facebook.com/obtuseorange", :class=>"image-responsive" %></p>
    </div>

</div>

</body>
</html>

app/views/layouts/application.html.erb.BASE.3486.erb
<!DOCTYPE html>
<html>
<html lang="en">
<head>
  <title>BrainStorm</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap-theme", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">   <!-- For navbar-->

 <!-- Brand and toggle get grouped for better mobile display -->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
    </button>
  <div class="navbar-brand"><%= link_to "BrainStorm", root_path, id: 'logo' %></div>
     </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
           <li><%= link_to "Rules", root_path %></li>
           <li><%= link_to "Forum", root_path %></li>
          
      <% if current_user.try(:admin?) %>
         <li><%= link_to "Make Game", admin_path %></li>
      <% end %>
          <li><%= link_to "LeaderBoard", leaderboard_path %></li>

      <% if user_signed_in? %>
          <li><%= link_to "Play Game", play_path%></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete  %></li>
      <% else %> 
          <li><%= link_to "Sign In", user_session_path %></li>
          <li><%= link_to "SignUp", new_user_registration_path %></li>
      <% end %>
      </ul>
     </div> 
    </nav>


   <div class ="container"><!--for container-->
        <% if flash[:notice] %>
     <div class = "alert alert-info">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:notice] %>
     </div>
     <% end %>
     <% if flash[:alert] %>
     <div class = "alert alert-danger">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:alert] %>
     </div>
     <% end %>
  
<%= yield %>

</div>

</body>
</html>

app/views/layouts/application.html.erb.LOCAL.3486.erb
<!DOCTYPE html>
<html>
<html lang="en">
<head>
  <title>BrainStorm</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap-theme", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">   <!-- For navbar-->

 <!-- Brand and toggle get grouped for better mobile display -->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
    </button>
  <div class="navbar-brand"><%= link_to image_tag("bsheader.png"), root_path, id: 'logo' %></div>
     </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
           <li><%= link_to "Rules", rules_path %></li>
           <li><%= link_to "Forum", root_path %></li>
          
      <% if current_user.try(:admin?) %>
         <li><%= link_to "Make Game", admin_path %></li>
      <% end %>
          <li><%= link_to "LeaderBoard", leaderboard_path %></li>

      <% if user_signed_in? %>
          <li><%= link_to "Play Game", play_path%></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete  %></li>
      <% else %> 
          <li><%= link_to "Sign In", user_session_path %></li>
          <li><%= link_to "SignUp", new_user_registration_path %></li>
      <% end %>
      </ul>
     </div> 
    </nav>


   <div class ="container"><!--for container-->
        <% if flash[:notice] %>
     <div class = "alert alert-info">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:notice] %>
     </div>
     <% end %>
     <% if flash[:alert] %>
     <div class = "alert alert-danger">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:alert] %>
     </div>
     <% end %>
  
<%= yield %>

    <div class="col-md-12 col-xs-12 col-lg-12">
      <hr>
      <p>Our Sponsor: <%= link_to image_tag("obtuseorange.png"), "http://www.facebook.com/obtuseorange", :class=>"image-responsive" %></p>
    </div>

</div>

</body>
</html>

app/views/layouts/application.html.erb.LOCAL.3837.erb
<!DOCTYPE html>
<html>
<html lang="en">
<head>
  <title>BrainStorm</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap-theme", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">   <!-- For navbar-->

 <!-- Brand and toggle get grouped for better mobile display -->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
    </button>
  <div class="navbar-brand"><%= link_to image_tag("bsheader.png"), root_path, id: 'logo' %></div>
     </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
           <li><%= link_to "Rules", rules_path %></li>
           <li><%= link_to "Forum", root_path %></li>
          
      <% if current_user.try(:admin?) %>
         <li><%= link_to "Make Game", admin_path %></li>
      <% end %>
          <li><%= link_to "LeaderBoard", leaderboard_path %></li>

      <% if user_signed_in? %>
          <li><%= link_to "Play Game", play_path%></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete  %></li>
      <% else %> 
          <li><%= link_to "Sign In", user_session_path %></li>
          <li><%= link_to "SignUp", new_user_registration_path %></li>
      <% end %>
      </ul>
     </div> 
    </nav>


   <div class ="container"><!--for container-->
        <% if flash[:notice] %>
     <div class = "alert alert-info">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:notice] %>
     </div>
     <% end %>
     <% if flash[:alert] %>
     <div class = "alert alert-danger">
       <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
       <%= flash[:alert] %>
     </div>
     <% end %>
  
<%= yield %>

    <div class="col-md-12 col-xs-12 col-lg-12">
      <hr>
      <p>Our Sponsor: <%= link_to image_tag("obtuseorange.png"), "http://www.facebook.com/obtuseorange", :class=>"image-responsive" %></p>
    </div>

</div>

</body>
</html>